### ISSUE TITLE
TODO: Implement file uploading system

### ISSUE THREAD

**Issue by Jam-Manbo** [Manbo-js/manbo#3]
Quote: [Uploading Files](https://discord.com/developers/docs/reference#uploading-files)

- [ ] Deprecate outdated file system in `Client`
- [ ] Support `file` in `requestHandler`
- [ ] Add new deprecated warning comment in `emitDeprecation`
